version: "3"
services:
  gateway:
    container_name: iot-gateway
    image: guccionfleek/iot-gateway
    volumes:
      - .:/home/gateway/.mozilla-iot
    ports:
      - "8080:8080"
      - "4443:4443"
