# https://github.com/gucci-on-fleek/IoT-Gateway-for-Docker
version: "3"
services:
  gateway:
    container_name: iot-gateway
    image: guccionfleek/iot-gateway
    restart: unless-stopped
    volumes:
      - .:/home/gateway/.webthings
    network_mode: "host"
