version: "3.7"
services:
  gateway:
    container_name: iot-gateway
    image: guccionfleek/iot-gateway
    restart: unless-stopped
    volumes:
      - .:/home/gateway/.mozilla-iot
    network_mode: "host"
