version: "3.7"
services:
  gateway:
    container_name: iot-gateway
    image: guccionfleek/iot-gateway
    restart: unless-stopped
    volumes:
      - .:/home/gateway/.mozilla-iot
    ports:
      - "8080:8080"
      - "4443:4443"
