name: Docker Image CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: "15 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Build the Docker image for testing
        run: docker build . --file Dockerfile --tag test-gateway
      - name: Test the Docker image
        run: ./test.py
      - name: Login to Docker
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Build and push the Docker image for all architectures
        run: ./build.sh
      - name: Update readme.md on Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./update-readme.sh
